import { makeContentProxy } from "../i18n"

const ZH = {
  page: {
    title: "推送日程",
    user_label: "用户",
    query_button: "查询",
    loading_button: "加载中…",
    err_pick_user: "请选择用户",
  },
  source: {
    digest: "Digest",
    cron_job: "自定义",
  },
  card: {
    actor: "用户主体",
    timezone: "时区",
    quiet_hours: "勿扰时段",
    quiet_disabled: "未启用",
    quiet_exempt_prefix: "豁免：{kinds}",
    immediate: "即时推",
    event_engine_enabled: "系统事件引擎：✅ 启用",
    event_engine_disabled: "系统事件引擎：❌ 已停用（用户设置会保留，但当前不会执行）",
    immediate_enabled: "✅ 启用",
    immediate_disabled: "❌ 已禁用",
    immediate_min_prefix: " · 最低：",
    immediate_only_portfolio: " · 仅持仓相关",
    price_ladder: "价格阶梯（最终生效）",
    price_up: "上涨首次 +{first}%，之后至少每前进 {step} 个百分点",
    price_down: "下跌首次 -{first}%，之后至少每前进 {step} 个百分点",
    price_candidate_grid: "系统候选档：{first}% 起、每 {step} 个百分点一档",
    price_daily_cap: "每日每类 High 最多 {cap} 条；价格阶梯超出后进入摘要",
    price_daily_cap_disabled: "每日 High 上限未启用",
    price_cooldown: "普通同标的 High 冷却 {minutes} 分钟；盘中价格阶梯豁免，按重复步长控频",
    price_cooldown_disabled: "普通同标的 High 冷却未启用",
    price_globally_disabled: "⚠ 系统已全局关闭 price_alert，上述价格阶梯当前不会执行",
    price_engine_disabled: "⚠ 系统事件引擎已停用，上述价格阶梯当前不会执行",
  },
  table: {
    col_time: "时刻",
    col_type: "类型",
    col_content: "内容",
    col_freq: "频率",
    col_active: "当日生效",
    col_hint: "操作提示",
    empty: "无定时推送（所有事件走即时推）",
    cell_quiet_held: "🌙 勿扰暂存",
    cell_bypass_quiet: "✅ 勿扰豁免",
    cell_active: "✅",
  },
  filters: {
    globally_disabled_kinds: "系统全局关闭事件类型：",
    blocked_kinds: "屏蔽事件类型：",
    allow_kinds: "接收事件类型：",
    exempt_in_quiet: "勿扰豁免事件类型：",
  },
}

const EN: typeof ZH = {
  page: {
    title: "Push schedule",
    user_label: "User",
    query_button: "Query",
    loading_button: "Loading…",
    err_pick_user: "Pick a user first.",
  },
  source: {
    digest: "Digest",
    cron_job: "Custom",
  },
  card: {
    actor: "User",
    timezone: "Timezone",
    quiet_hours: "Quiet hours",
    quiet_disabled: "Disabled",
    quiet_exempt_prefix: "Exempt: {kinds}",
    immediate: "Immediate",
    event_engine_enabled: "System event engine: ✅ enabled",
    event_engine_disabled: "System event engine: ❌ disabled (user settings are retained but do not currently run)",
    immediate_enabled: "✅ Enabled",
    immediate_disabled: "❌ Disabled",
    immediate_min_prefix: " · min severity: ",
    immediate_only_portfolio: " · portfolio-only",
    price_ladder: "Price ladder (effective)",
    price_up: "Up: first at +{first}%, then at least {step}pp farther",
    price_down: "Down: first at -{first}%, then at least {step}pp farther",
    price_candidate_grid: "System candidate bands start at {first}% in {step}pp steps",
    price_daily_cap: "At most {cap} High pushes per event category each day; extra price bands go to the digest",
    price_daily_cap_disabled: "The daily High cap is disabled",
    price_cooldown: "Ordinary High events for the same symbol cool down for {minutes} minutes; intraday price bands are exempt and use the repeat step instead",
    price_cooldown_disabled: "The ordinary same-symbol High cooldown is disabled",
    price_globally_disabled: "⚠ price_alert is globally disabled; the price ladder above does not currently run",
    price_engine_disabled: "⚠ The system event engine is disabled; the price ladder above does not currently run",
  },
  table: {
    col_time: "Time",
    col_type: "Type",
    col_content: "Content",
    col_freq: "Frequency",
    col_active: "Today",
    col_hint: "Edit hint",
    empty: "No scheduled pushes (all events are sent immediately).",
    cell_quiet_held: "🌙 Held by quiet hours",
    cell_bypass_quiet: "✅ Bypasses quiet hours",
    cell_active: "✅",
  },
  filters: {
    globally_disabled_kinds: "Globally disabled event types: ",
    blocked_kinds: "Muted event types: ",
    allow_kinds: "Events received: ",
    exempt_in_quiet: "Quiet-hours exemptions: ",
  },
}

export const SCHEDULE = makeContentProxy(ZH, EN)
export const __SCHEDULE_TREES__ = { zh: ZH, en: EN } as const
