// admin-content/settings.ts — bilingual labels for the Settings page.
//
// Only strings consumed by `pages/settings.tsx` belong here. Both ZH and EN
// trees share the exact same shape — `structure.test.ts` enforces parity.

import { makeContentProxy } from "../i18n"

const ZH = {
  language: {
    title: "界面语言",
    subtitle: "选择控制台语言。保存后写入 config.yaml，所有连接到该后端的设备首次加载使用此语言。",
    option_zh: "中文",
    option_en: "English",
    save: "保存",
    saving: "保存中…",
    saved: "已保存",
    save_failed: "保存失败",
    no_change: "未更改",
    note:
      "侧边栏切换器只影响当前设备，本设置才会写入 config.yaml 决定其他设备的默认语言。",
  },
  tabs: {
    agent: "Agent",
    data: "数据源",
    notify: "通知",
    channel: "渠道",
    invite: "邀请码",
  },
  agent: {
    title: "基础设置",
    subtitle: "选择 Agent 引擎并配置相关参数，保存后立即写入运行时配置。",
    current_badge: "当前",
    hone_cloud: {
      name: "Hone Cloud",
      description:
        "使用 hone-claw.com 托管用户端配置与生产服务运行对话，可填写用户 API Key 或自定义服务地址。",
      base_url_label: "服务地址",
      model_label: "模型",
      api_key_label: "API Key",
      contact_note: "如需邀请码或 API Key，请联系 bm@hone-claw.com。",
      hide: "隐藏",
      show: "显示",
      test_connection: "测试连通",
      testing: "测试中…",
      connection_testing_status: "Hone Cloud 连通测试中，请稍候…",
      save: "保存",
      saving: "保存中…",
    },
    multi_agent: {
      name: "Multi-Agent",
      description:
        "Search Agent 使用 MiniMax function calling，Answer Agent 使用 opencode ACP 收束回复",
      search_title: "Search Agent (MiniMax / OpenAI-compatible)",
      answer_title: "Answer Agent (OpenAI-compatible via opencode ACP)",
      test_search: "测试 Search Agent",
      test_answer: "测试 Answer Agent",
      check_opencode: "检查 opencode",
      testing: "测试中…",
      checking: "检测中…",
      hide: "隐藏",
      show: "显示",
    },
    openai: {
      name: "OpenAI 协议渠道",
      description:
        "兼容 OpenRouter、OpenAI 及任意 OpenAI-compatible 端点（通过 opencode acp 驱动）",
      base_url_label: "Base URL",
      model_label: "主模型",
      api_key_label: "API Key",
      auxiliary_title: "Auxiliary 子模型链路",
      auxiliary_subtitle:
        "用于心跳检测、会话压缩等后台辅助任务，支持独立的 OpenAI-compatible Base URL / API Key / Model。",
      auxiliary_url_label: "Auxiliary Base URL",
      auxiliary_model_label: "Auxiliary Model",
      auxiliary_apikey_label: "Auxiliary API Key",
      profiles_title: "LLM Profile 路由",
      profiles_subtitle:
        "按用途选择模型 symbol；运行时会用对应 profile 的 provider、model 与参数发起请求。",
      profiles_default_label: "默认对话",
      profiles_auxiliary_label: "辅助任务",
      profiles_polish_label: "消息润色",
      profiles_news_label: "新闻分类",
      profiles_filing_label: "公告摘要",
      profiles_earnings_label: "财报质检",
      profiles_digest_pass1_label: "Digest 初筛",
      profiles_digest_pass2_label: "Digest 个性化",
      profiles_digest_dedupe_label: "Digest 去重",
      profiles_mainline_label: "主线摘要",
      profiles_provider_label: "Provider",
      profiles_model_label: "Model",
      profiles_max_tokens_label: "Max tokens",
      profiles_temperature_label: "Temperature",
      profiles_top_p_label: "Top P",
      profiles_reasoning_label: "Reasoning",
      profiles_reasoning_tokens_label: "Reasoning tokens",
      profiles_json_label: "JSON",
      hide: "隐藏",
      show: "显示",
      test_connection: "测试连通",
      test_auxiliary: "测试 Auxiliary",
      testing: "测试中…",
      auxiliary_testing_status: "Auxiliary 连通测试中，请稍候…",
      connection_testing_status: "连通测试中，请稍候…",
      save: "保存",
      saving: "保存中…",
    },
    codex_acp: {
      name: "Codex ACP",
      description_prefix: "使用 ",
      description_code: "codex-acp",
      description_suffix: " 驱动当前 Agent，会话实际走 ACP 链路而不是 multi-agent。",
      runtime_note:
        "运行时配置当前来自 desktop canonical / effective config；如果 live listener 仍显示旧 runner，应继续核对 release sidecar 是否已按新配置重启。",
      checking_status: "检测中，请稍候…",
      test_connection: "测试连通",
      checking: "检测中…",
    },
    gemini_cli: {
      name: "Gemini CLI",
      description_prefix: "使用本机安装的 ",
      description_code: "gemini",
      description_suffix: " 命令行 Agent",
      checking_status: "检测中，请稍候…",
      test_connection: "测试连通",
      checking: "检测中…",
    },
    codex_cli: {
      name: "Codex",
      description_prefix: "使用本机安装的 ",
      description_code: "codex",
      description_suffix: " 命令行 Agent",
      checking_status: "检测中，请稍候…",
      test_connection: "测试连通",
      checking: "检测中…",
    },
  },
  data: {
    title: "API 配置",
    subtitle: "配置各类数据源和搜索服务的密钥。支持多 Key 轮换及自动重试。",
    fmp: {
      name: "金融数据 API (Financial Modeling Prep)",
      description: "用于获取实时股票、报表等金融核心数据",
      key_placeholder: "FMP API Key",
      remove: "删除",
      add_key: "+ 添加 Key",
      save: "保存 FMP",
      saving: "保存中…",
      saved: "已保存 FMP API key，内置后端已重启生效",
    },
    tavily: {
      name: "搜索 API (Tavily)",
      description: "用于联网获取最新信息、文章、网页内容",
      key_placeholder: "tvly-...",
      remove: "删除",
      add_key: "+ 添加 Key",
      save: "保存 Tavily",
      saving: "保存中…",
      saved: "已保存 Tavily API key，内置后端已重启生效",
    },
  },
  notify: {
    title: "通知推送偏好",
    subtitle: "代任意 actor 调整事件推送策略。终端用户自己也可以在渠道里用自然语言调整。",
  },
  channel: {
    title: "渠道设置",
    subtitle: "开启后 Hone 会通过对应渠道监听消息并进行 Agent 响应。",
    refresh: "刷新配置",
    common: {
      chat_scope_label: "会话范围",
      allow_from_label: "允许用户",
      allow_emails_label: "允许邮箱",
      allow_mobiles_label: "允许手机号",
      allow_open_ids_label: "允许 open_id",
      target_handle_label: "监听对象",
      csv_placeholder: "逗号分隔；留空表示全部允许",
    },
    feishu: {
      name: "飞书 (Feishu)",
      app_id_label: "App ID",
      app_id_placeholder: "cli_...",
      app_secret_label: "App Secret",
      app_secret_placeholder: "Secret",
      hide: "隐藏",
      show: "显示",
    },
    discord: {
      name: "Discord",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Discord Bot Token",
      hide: "隐藏",
      show: "显示",
    },
    telegram: {
      name: "Telegram",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Token",
      hide: "隐藏",
      show: "显示",
    },
    imessage: {
      name: "iMessage",
      warning: "⚠️ Needs Full Disk Access",
    },
    sync_note: "保存后配置文件立即更新；CLI 启动的监听进程需重启后应用启停变化。",
    save: "同步全部渠道",
    saving: "同步中…",
  },
  invite: {
    title: "Web 用户邀请码",
    subtitle:
      "生成邀请码时会同步创建一个 `web` 用户，并将邀请码与手机号强绑定。用户通过 `/chat` 输入邀请码和手机号登录后，复用现有 12 次对话额度限制。",
    refresh: "刷新",
    phone_label: "手机号",
    phone_placeholder: "生成邀请码前先输入手机号",
    create: "生成邀请码",
    creating: "生成中…",
    phone_required: "请输入手机号",
    created: "已为 {phone} 生成邀请码 {code}",
    created_copied: "已为 {phone} 生成并复制邀请码 {code}",
    created_with_api_key: "已为 {phone} 生成邀请码 {code} 和 API Key {apiKey}",
    created_with_api_key_copied: "已为 {phone} 生成邀请码 {code} 和 API Key，并已复制",
    copied: "已复制邀请码 {code}",
    copy_unsupported: "当前环境不支持复制",
    disable_confirm: "停用 {userId} 的邀请码后，现有 Web 登录态会立即失效。继续吗？",
    reset_confirm:
      "将为 {userId} 生成新邀请码，并让旧邀请码和现有 Web 登录态立即失效。继续吗？",
    api_key_reset_confirm:
      "将为 {userId} 生成新的 API Key，旧 API Key 会立即失效，但不会清理登录态。继续吗？",
    reset_copied_suffix: "{message}，新邀请码已复制",
    api_key_copied: "API Key 已复制。明文只显示一次，请妥善保存。",
    table: {
      code: "邀请码",
      phone: "手机号",
      web_user: "Web 用户",
      status: "状态",
      api_key: "API Key",
      sessions: "登录态",
      remaining: "剩余次数",
      last_login: "最近登录",
      actions: "操作",
      empty: "还没有生成任何邀请码。",
      phone_unbound: "未绑定",
      enabled: "已启用",
      disabled: "已停用",
      unlimited: "不限",
      never_logged_in: "未登录",
      api_key_missing: "未生成",
      copy: "复制",
      reset: "重置",
      resetting: "重置中…",
      api_key_get: "获取 Key",
      api_key_getting: "获取中…",
      api_key_reset: "重置 Key",
      api_key_resetting: "重置中…",
      enable: "启用",
      enabling: "启用中…",
      disable: "停用",
      disabling: "停用中…",
    },
  },
}

const EN: typeof ZH = {
  language: {
    title: "Language",
    subtitle:
      "Choose the console language. Saving writes to config.yaml — all devices connecting to this backend will pick up this default on first load.",
    option_zh: "中文",
    option_en: "English",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    save_failed: "Save failed",
    no_change: "No change",
    note:
      "The sidebar switcher only affects the current device. This setting writes to config.yaml and decides the default language on other devices.",
  },
  tabs: {
    agent: "Agent",
    data: "Data sources",
    notify: "Notifications",
    channel: "Channels",
    invite: "Invite codes",
  },
  agent: {
    title: "Core settings",
    subtitle:
      "Pick the agent runner and configure its parameters. Saving writes to runtime config immediately.",
    current_badge: "Active",
    hone_cloud: {
      name: "Hone Cloud",
      description:
        "Uses the hone-claw.com hosted user configuration and production service. Enter a user API key or customize the service URL.",
      base_url_label: "Service URL",
      model_label: "Model",
      api_key_label: "API Key",
      contact_note: "Contact bm@hone-claw.com for an invite code or API key.",
      hide: "Hide",
      show: "Show",
      test_connection: "Test connection",
      testing: "Testing…",
      connection_testing_status: "Testing Hone Cloud connection, please wait…",
      save: "Save",
      saving: "Saving…",
    },
    multi_agent: {
      name: "Multi-Agent",
      description:
        "Search Agent uses MiniMax function calling; Answer Agent finalizes the reply via opencode ACP.",
      search_title: "Search Agent (MiniMax / OpenAI-compatible)",
      answer_title: "Answer Agent (OpenAI-compatible via opencode ACP)",
      test_search: "Test Search Agent",
      test_answer: "Test Answer Agent",
      check_opencode: "Check opencode",
      testing: "Testing…",
      checking: "Checking…",
      hide: "Hide",
      show: "Show",
    },
    openai: {
      name: "OpenAI-compatible channel",
      description:
        "Works with OpenRouter, OpenAI, and any OpenAI-compatible endpoint (driven by opencode acp).",
      base_url_label: "Base URL",
      model_label: "Primary model",
      api_key_label: "API Key",
      auxiliary_title: "Auxiliary sub-model",
      auxiliary_subtitle:
        "Used for heartbeat checks, session compaction, and other background helpers. Accepts an independent OpenAI-compatible Base URL / API Key / Model.",
      auxiliary_url_label: "Auxiliary Base URL",
      auxiliary_model_label: "Auxiliary Model",
      auxiliary_apikey_label: "Auxiliary API Key",
      profiles_title: "LLM profile routing",
      profiles_subtitle:
        "Choose model symbols per runtime use case; each profile carries its provider, model, and request parameters.",
      profiles_default_label: "Default chat",
      profiles_auxiliary_label: "Auxiliary tasks",
      profiles_polish_label: "Message polish",
      profiles_news_label: "News classifier",
      profiles_filing_label: "Filing summary",
      profiles_earnings_label: "Earnings review",
      profiles_digest_pass1_label: "Digest pass 1",
      profiles_digest_pass2_label: "Digest pass 2",
      profiles_digest_dedupe_label: "Digest dedupe",
      profiles_mainline_label: "Mainline distill",
      profiles_provider_label: "Provider",
      profiles_model_label: "Model",
      profiles_max_tokens_label: "Max tokens",
      profiles_temperature_label: "Temperature",
      profiles_top_p_label: "Top P",
      profiles_reasoning_label: "Reasoning",
      profiles_reasoning_tokens_label: "Reasoning tokens",
      profiles_json_label: "JSON",
      hide: "Hide",
      show: "Show",
      test_connection: "Test connection",
      test_auxiliary: "Test Auxiliary",
      testing: "Testing…",
      auxiliary_testing_status: "Testing Auxiliary connection, please wait…",
      connection_testing_status: "Testing connection, please wait…",
      save: "Save",
      saving: "Saving…",
    },
    codex_acp: {
      name: "Codex ACP",
      description_prefix: "Drives the current agent via ",
      description_code: "codex-acp",
      description_suffix: ". Sessions run over the ACP link instead of multi-agent.",
      runtime_note:
        "Runtime config currently comes from desktop canonical / effective config. If the live listener still shows the old runner, double-check that the release sidecar restarted with the new config.",
      checking_status: "Checking, please wait…",
      test_connection: "Test connection",
      checking: "Checking…",
    },
    gemini_cli: {
      name: "Gemini CLI",
      description_prefix: "Uses the locally installed ",
      description_code: "gemini",
      description_suffix: " CLI agent.",
      checking_status: "Checking, please wait…",
      test_connection: "Test connection",
      checking: "Checking…",
    },
    codex_cli: {
      name: "Codex",
      description_prefix: "Uses the locally installed ",
      description_code: "codex",
      description_suffix: " CLI agent.",
      checking_status: "Checking, please wait…",
      test_connection: "Test connection",
      checking: "Checking…",
    },
  },
  data: {
    title: "API configuration",
    subtitle:
      "Configure keys for data sources and search services. Multi-key rotation and auto retry are supported.",
    fmp: {
      name: "Financial data API (Financial Modeling Prep)",
      description: "Real-time quotes, fundamentals, and other core financial data.",
      key_placeholder: "FMP API Key",
      remove: "Remove",
      add_key: "+ Add key",
      save: "Save FMP",
      saving: "Saving…",
      saved: "FMP API keys saved; the embedded backend has restarted.",
    },
    tavily: {
      name: "Search API (Tavily)",
      description: "Live web search for fresh news, articles, and page content.",
      key_placeholder: "tvly-...",
      remove: "Remove",
      add_key: "+ Add key",
      save: "Save Tavily",
      saving: "Saving…",
      saved: "Tavily API keys saved; the embedded backend has restarted.",
    },
  },
  notify: {
    title: "Notification preferences",
    subtitle:
      "Adjust event push policy on behalf of any actor. End users can also tune this from the channel via natural language.",
  },
  channel: {
    title: "Channels",
    subtitle:
      "When enabled, Hone listens for messages on the channel and replies via the agent.",
    refresh: "Refresh",
    common: {
      chat_scope_label: "Chat scope",
      allow_from_label: "Allowed users",
      allow_emails_label: "Allowed emails",
      allow_mobiles_label: "Allowed mobiles",
      allow_open_ids_label: "Allowed open_ids",
      target_handle_label: "Tracked handle",
      csv_placeholder: "Comma-separated; empty means allow all",
    },
    feishu: {
      name: "Feishu (Lark)",
      app_id_label: "App ID",
      app_id_placeholder: "cli_...",
      app_secret_label: "App Secret",
      app_secret_placeholder: "Secret",
      hide: "Hide",
      show: "Show",
    },
    discord: {
      name: "Discord",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Discord Bot Token",
      hide: "Hide",
      show: "Show",
    },
    telegram: {
      name: "Telegram",
      bot_token_label: "Bot Token",
      bot_token_placeholder: "Token",
      hide: "Hide",
      show: "Show",
    },
    imessage: {
      name: "iMessage",
      warning: "⚠️ Needs Full Disk Access",
    },
    sync_note:
      "Saving updates the config file immediately; CLI-started listeners need a restart to apply enable/disable changes.",
    save: "Sync all channels",
    saving: "Syncing…",
  },
  invite: {
    title: "Web user invite codes",
    subtitle:
      "Generating an invite code also creates a `web` user bound to the phone number. After signing in via `/chat` with the invite code and phone number, the user shares the existing 12-message daily quota.",
    refresh: "Refresh",
    phone_label: "Phone number",
    phone_placeholder: "Enter the phone number before generating",
    create: "Generate invite code",
    creating: "Generating…",
    phone_required: "Enter a phone number",
    created: "Generated invite code {code} for {phone}",
    created_copied: "Generated and copied invite code {code} for {phone}",
    created_with_api_key: "Generated invite code {code} and API key {apiKey} for {phone}",
    created_with_api_key_copied:
      "Generated invite code {code} and API key for {phone}; both copied",
    copied: "Copied invite code {code}",
    copy_unsupported: "Clipboard not available in this environment",
    disable_confirm:
      "Disabling the invite for {userId} will immediately log out the existing web session. Continue?",
    reset_confirm:
      "This will issue a new invite code for {userId} and immediately invalidate the old code and any active web session. Continue?",
    api_key_reset_confirm:
      "This will issue a new API key for {userId}. The old API key stops working, but web sessions stay signed in. Continue?",
    reset_copied_suffix: "{message}; new invite code copied",
    api_key_copied: "API key copied. Plaintext is shown only once; store it securely.",
    table: {
      code: "Invite code",
      phone: "Phone",
      web_user: "Web user",
      status: "Status",
      api_key: "API Key",
      sessions: "Sessions",
      remaining: "Remaining",
      last_login: "Last login",
      actions: "Actions",
      empty: "No invite codes generated yet.",
      phone_unbound: "Not bound",
      enabled: "Enabled",
      disabled: "Disabled",
      unlimited: "Unlimited",
      never_logged_in: "Never",
      api_key_missing: "Not generated",
      copy: "Copy",
      reset: "Reset",
      resetting: "Resetting…",
      api_key_get: "Get key",
      api_key_getting: "Getting…",
      api_key_reset: "Reset key",
      api_key_resetting: "Resetting…",
      enable: "Enable",
      enabling: "Enabling…",
      disable: "Disable",
      disabling: "Disabling…",
    },
  },
}

export const SETTINGS = makeContentProxy(ZH, EN)

// Internal — exported only for the structure parity test.
export const __SETTINGS_TREES__ = { zh: ZH, en: EN } as const
