import { makeContentProxy } from "../i18n"

const ZH = {
  list: {
    title: "技能管理",
    subtitle: "注册表、启停状态与技能文档",
    counts_total: "总数 {count}",
    counts_enabled: "启用 {count}",
    counts_disabled: "禁用 {count}",
    counts_invocable: "Slash {count}",
    search_placeholder: "搜索 id、名称、alias",
    status_all: "全部",
    status_enabled: "已启用",
    status_disabled: "已禁用",
    source_all: "全部来源",
    source_system: "System",
    source_custom: "Custom",
    source_dynamic: "Dynamic",
    empty_title: "没有找到技能",
    empty_description: "请调整筛选条件,或检查 skills 目录与 SKILL.md。",
    toggle_enabled: "启用",
    toggle_disabled: "禁用",
    badge_disabled: "disabled",
    badge_slash: "slash",
  },
  detail: {
    header_title: "技能管理",
    header_subtitle: "查看当前注册的 skills,并控制它们是否可被 Hone 在所有渠道与 runners 中调用。",
    reset_button: "恢复默认",
    resetting_button: "恢复中...",
    counts_total: "总数 {count}",
    counts_enabled: "启用 {count}",
    counts_disabled: "禁用 {count}",
    counts_invocable: "Slash {count}",
    empty_title: "从左侧选择一个技能",
    empty_description: "这里会展示技能状态、运行时元信息和 Markdown 文档。",
    badge_slash: "slash",
    badge_script: "script",
    badge_path_gated: "path-gated",
    enable_label: "启用此技能",
    invoke_button: "在对话中触发",
    meta_loaded_from: "来源:{value}",
    meta_context: "执行上下文:{value}",
    meta_invocable: "Slash:{value}",
    meta_file: "文件:{value}",
    invocable_yes: "允许",
    invocable_no: "不允许",
    aliases_label: "Aliases",
    paths_label: "Path Gate",
    none: "无",
  },
}

const EN: typeof ZH = {
  list: {
    title: "Skills",
    subtitle: "Registry, enable state, and skill docs.",
    counts_total: "Total {count}",
    counts_enabled: "Enabled {count}",
    counts_disabled: "Disabled {count}",
    counts_invocable: "Slash {count}",
    search_placeholder: "Search id, name, alias",
    status_all: "All",
    status_enabled: "Enabled",
    status_disabled: "Disabled",
    source_all: "All sources",
    source_system: "System",
    source_custom: "Custom",
    source_dynamic: "Dynamic",
    empty_title: "No skills found",
    empty_description: "Adjust your filters, or check the skills directory and SKILL.md.",
    toggle_enabled: "Enabled",
    toggle_disabled: "Disabled",
    badge_disabled: "disabled",
    badge_slash: "slash",
  },
  detail: {
    header_title: "Skills",
    header_subtitle: "View registered skills and control whether Hone can invoke them across channels and runners.",
    reset_button: "Restore defaults",
    resetting_button: "Restoring…",
    counts_total: "Total {count}",
    counts_enabled: "Enabled {count}",
    counts_disabled: "Disabled {count}",
    counts_invocable: "Slash {count}",
    empty_title: "Select a skill on the left",
    empty_description: "Skill status, runtime metadata, and Markdown docs will appear here.",
    badge_slash: "slash",
    badge_script: "script",
    badge_path_gated: "path-gated",
    enable_label: "Enable this skill",
    invoke_button: "Run in chat",
    meta_loaded_from: "Source: {value}",
    meta_context: "Context: {value}",
    meta_invocable: "Slash: {value}",
    meta_file: "File: {value}",
    invocable_yes: "Allowed",
    invocable_no: "Not allowed",
    aliases_label: "Aliases",
    paths_label: "Path gate",
    none: "None",
  },
}

export const SKILLS = makeContentProxy(ZH, EN)
export const __SKILLS_TREES__ = { zh: ZH, en: EN } as const
